### ISSUE TITLE
error- Remove is not a function

### ISSUE THREAD

**Issue by pete0959** [mbrookson/react-simple-hook-modal#23]
Followed your example - get the error "remove is not a function"

**Comment by MorganaTBorges** [comment]
me too!

**Comment by asdaviid** [comment]
@pete0959 @MorganaTBorges Did you remember to wrap the App in the <ModalProvider> component?

Refer to https://github.com/mbrookson/react-simple-hook-modal#react

**Comment by mbrookson** [comment]
Thanks @asdaviid!

@pete0959 @MorganaTBorges The `remove` function is provided by the `ModalProvider` so make sure you have `<ModalProvider />` wrapping all your modals. The simplest away to achieve this is to wrap your entire app component, as is common with a number of other providers.

Hope this helps!
