### ISSUE TITLE
Increase z-index or allow custom

### ISSUE THREAD

**Issue by mbrookson** [mbrookson/react-simple-hook-modal#9]
Using tailwind's z-index classes doesn't really work since it only goes up to z-50.

Generally this should be okay, but some elements have a far greater z-index than this, but the modal should always be on top.

Increase the z-index to a larger number, perhaps 1000 to ensure it's always on top?

Could also add a prop to `<ModalProvider />` to allow this to be overridden globally in case the user has z-indexes even greater than this.

**Comment by damiensedgwick** [comment]
From the tailwind docs you should just be able to add your own z-index value in the config and call it like a normal class:

```code
// tailwind.config.js
  module.exports = {
    theme: {
      zIndex: {
        '0': 0,
       '10': 10,
       '20': 20,
       '30': 30,
       '40': 40,
       '50': 50,
       '25': 25,
       '50': 50,
       '75': 75,
       '100': 100,
        'auto': 'auto',
      }
    }
  }
```

I was doing something similar today but with grid-rows-{n}. Could be a quick fix. Happy to test in a PR if you like?

**Comment by mbrookson** [comment]
@damiensedgwick yeah could do that. Probably just need to add one that's a high number. Then still think adding a config option would be a good idea in case someone has another higher z-index element that they want to cover.
PR welcomed if you fancy it!

**Comment by damiensedgwick** [comment]
I've opened up a PR here #32

**Comment by mbrookson** [comment]
Fixed by https://github.com/mbrookson/react-simple-hook-modal/pull/32
